# Generated by Django 4.2.6 on 2023-10-10 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tenant_landlord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='house',
        ),
        migrations.AddField(
            model_name='house',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.landlord'),
        ),
    ]
