# Generated by Django 4.2.6 on 2023-10-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_paymentlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
    ]
