# Generated by Django 4.2.6 on 2023-10-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_landlord_house_house_landlord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='user',
        ),
    ]
