# Generated by Django 4.2.6 on 2023-10-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
