# Generated by Django 4.2.6 on 2023-10-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_house_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
    ]
