# Generated by Django 4.2.6 on 2023-10-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_tenant_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TenantRentPayment',
            new_name='Payment',
        ),
    ]
