# Generated by Django 4.2.6 on 2023-10-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tenant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='image',
            field=models.ImageField(default=4, upload_to='tenants/images'),
            preserve_default=False,
        ),
    ]
