# Generated by Django 4.2.6 on 2023-10-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_tenant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='image',
            field=models.ImageField(null=True, upload_to='tenants/images'),
        ),
    ]
