# Generated by Django 4.2.6 on 2023-10-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_tenant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(null=True, upload_to='house/images'),
        ),
    ]
